name: Continuous Integration for dianaflorez

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Pruebas de SAST (mockeado con un echo)
      - name: Pruebas de SAST
        run: echo "EjecuciÃ³n de pruebas de SAST"

      # Paso 2: Instalar Docker (opcional, por si hay problemas con Docker)
      - name: Instalar Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      # Paso 3: Crear archivo de credenciales
      - name: Crear archivo de credenciales
        run: |
          echo "[Credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      # Paso 4: Build docker image
      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)

