name : continuous-integration
env:
  USERNAME: '${{ secrets.USERNAME }}'
  PASSWORD: '${{ secrets.PASSWORD }}'
on : [push]
jobs:
  Pruebas-de-SAST:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ejecuci√≥n de pruebas de SAST"
  Crea-file-credenciales:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.USERNAME }}"
      - run: echo "Crea credenciales file"
 
     
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:    
      - run: echo "Construye docker"
      - run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
