name: practica-3-threepoints-ci-cd
run-name: ${{ github.actor }} - Practica 3 - Threepoints - CI/CD
on: [push]
jobs:
  continous-integration-andres-ospina:
    if: github.ref_name == 'master' || startsWith(github.ref_name,'feature') || startsWith(github.ref_name,'hotfix')
    runs-on: ubuntu-latest    
    steps:    
    - name: Pruebas de SAST      
      run: echo "Ejecucion de pruebas de SAST sobre la rama ${GITHUB_REF_NAME}"
    - uses: actions/checkout@v2.3.4
    - uses: GuillaumeFalourd/command-output-file-action@v1.1        
      name: Archivo Credenciales    
      with:
          command_line: echo "[credentials] username=${{ secrets.PASSWORD }} | password=${{ secrets.PASSWORD }}"
          output_file_name: credentials.ini
          display_file_content: YES
    - name: Build docker image
      run: docker build -t devops_ws . --tag devops_ws_$(date +%s)