
name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"
      
      - name: Generar archivo credentials.ini
        env:
          USERNAME: '${{ secrets.USERNAME }}'
          PASSWORD: '${{ secrets.PASSWORD}}'
        run: envsubst < credentials.ini.tpl > credentials.ini

      - name: Almacenamiento artefacto de credentials.ini
        uses: actions/upload-artifact@v3
        with:
          name: credentials-almacenamiento
          path: credentials.ini

      - name: Construcción del contenedor Docker
        run: docker build -t devops_ws . --tag devops_ws_$(date +%s)




