name : continuous-integration
env:
  USERNAME: '${{ secrets.USERNAME }}'
  PASSWORD: '${{ secrets.PASSWORD }}'
on: 
  push:
    branches:
      - 'master'
jobs:
  Pruebas-de-SAST:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ejecuci√≥n de pruebas de SAST"
  Crea-file-credenciales:
    runs-on: ubuntu-latest
    defaults:
      run :
         working-directory: .
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.3.4
      - run: envsubst < credentials.ini.tpl > credentials.ini
      - run: git config --global user.name "JLCalderonB"
      - run: git add .
      - run: git commit -m "crea credentials.ini en Pipeline"
      - run: git push
      - run: echo "Crea credenciales file"
 
     
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - run: echo "Construye docker"
      - run: docker build -t devops_ws . --tag devops_ws:$(date +%s)
