name: Continuous Integration

on:
  push:
    branches:
      - master  # Se ejecuta cuando hay un push a master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pruebas de SAST
      - name: Pruebas de SAST
        run: echo "EjecuciÃ³n de pruebas de SAST"
      
      # 2. Crear archivo de credenciales
      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "user=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      # 3. Construir la imagen de Docker
      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
